spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: false
        use_sql_comments: true
  output:
    ansi:
      enabled: always

logging:
  level:
    com.example.demo: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: debug
